---
all:
    hosts:
        web:
            ansible_host: 192.168.56.120
            ansible_user: vagrant
            enable_web: "yes"
        collector1:
            ansible_host: 192.168.56.121
            ansible_user: vagrant
            messagebus: rmq
        collector2:
            ansible_host: 192.168.56.122
            ansible_user: vagrant
